# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql2
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000


development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: web_support_development
  pool: 5
  username: root
  password: root
  # socket: /Applications/MAMP/tmp/mysql/mysql.sock
 # socket: /tmp/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: web_support_test
  pool: 5
  username: root
  password: root
  # socket: /Applications/MAMP/tmp/mysql/mysql.sock
  #socket: /tmp/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: web_support_production
  pool: 5
  username: root
  password: root
  # socket: /Applications/MAMP/tmp/mysql/mysql.sock
  #socket: /tmp/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

